apiVersion: v1
kind: Service
metadata:
  name: guacd
  labels:
    run: guacd
spec:
  ports:
  - port: 4822
    protocol: TCP
  selector:
    run: guacd

---

apiVersion: v1
kind: Service
metadata:
  name: guacamole
  labels:
    run: guacamole
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: guacamole
